name: Test and Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]  # puedes ajustar versiones según tu proyecto

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Run tests with pytest
      working-directory: src
      run: |
        pytest -v  # -v muestra más detalle en los resultados
